# Generated by Django 5.2.13 on 2026-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('hsn_sac_code', models.CharField(default='9992', max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_gst_invoice',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=36, max_digits=10)),
                ('gateway_charge', models.DecimalField(decimal_places=2, default=5.72, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=241.72, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sponsor_slot_redemption', models.BooleanField(default=False)),
                ('is_retail_purchase', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20)),
                ('gst_invoice_number', models.CharField(blank=True, max_length=40, null=True)),
                ('refund_eligible_until', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_order',
            },
        ),
    ]
