# Generated by Django 5.2.13 on 2026-04-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('sponsor_slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sponsor_code_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_using_code', to='sponsor_slots.sponsorslotcode'),
        ),
    ]
