# Generated by Django 5.2.13 on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_ebook_catalog_fields"),
        ("payments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ebook",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="courses.ebook",
            ),
        ),
    ]
