# Generated by Django 5.2.13 on 2026-05-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_order_placement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placement_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending manual or auto placement'), ('PLACED_MANUAL', 'Placed by sponsor'), ('PLACED_AUTO', 'Placed by auto job'), ('PLACED_ADMIN', 'Placed by admin'), ('FAILED', 'Placement failed')], max_length=32, null=True),
        ),
    ]
