# Generated by Django 5.2.13 on 2026-05-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_ebook_catalog_fields'),
        ('payments', '0007_order_billing_and_invoice_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='courses.ebook')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.order')),
            ],
            options={
                'db_table': 'payments_orderline',
                'constraints': [models.UniqueConstraint(fields=('order', 'ebook'), name='uniq_orderline_order_ebook')],
            },
        ),
    ]
