# Generated by Django 5.2.13 on 2026-05-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_refundrequest_razorpay_refund_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refundrequest',
            new_name='payments_re_status_2707fa_idx',
            old_name='payments_re_status_d55b59_idx',
        ),
        migrations.RenameIndex(
            model_name='refundrequest',
            new_name='payments_re_user_id_ac5e9d_idx',
            old_name='payments_re_user_id_82e6ad_idx',
        ),
    ]
