# Generated by Django 5.2 on 2026-05-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_refundrequest_order_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("credit_note_number", models.CharField(max_length=40, unique=True)),
                ("hsn_sac_code", models.CharField(default="9992", max_length=10)),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cgst", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sgst", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_gst", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("grand_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(default="refund", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gst_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="payments.gstinvoice",
                    ),
                ),
                (
                    "refund_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note",
                        to="payments.refundrequest",
                    ),
                ),
            ],
            options={
                "db_table": "payments_credit_note",
                "indexes": [
                    models.Index(fields=["-created_at"], name="payments_cr_created_6e2a0d_idx"),
                    models.Index(
                        fields=["gst_invoice", "-created_at"],
                        name="payments_cr_gst_inv_8f3c21_idx",
                    ),
                ],
            },
        ),
    ]
