# Generated by Django 5.2 on 2026-05-27

from datetime import date
from decimal import Decimal

from django.db import migrations
from django.utils import timezone


Q2 = Decimal("0.01")


def _indian_fy_start(containing: date) -> date:
    y = containing.year
    if containing.month >= 4:
        return date(y, 4, 1)
    return date(y - 1, 4, 1)


def _refund_proportion(amount, cap):
    cap = Decimal(str(cap or 0)).quantize(Q2)
    amount = Decimal(str(amount or 0)).quantize(Q2)
    if cap <= Decimal("0"):
        return Decimal("1")
    return min((amount / cap).quantize(Decimal("0.0001")), Decimal("1"))


def _amount_paid_share_by_line(order, OrderLine):
    lines = list(OrderLine.objects.filter(order_id=order.pk).order_by("id").only("id", "unit_base_price"))
    if not lines:
        return {}
    ap = Decimal(str(order.amount_paid)).quantize(Q2)
    tot = sum((Decimal(str(ln.unit_base_price)) for ln in lines), Decimal("0")).quantize(Q2)
    out = {}
    if tot <= 0:
        n = len(lines)
        acc = Decimal("0")
        for i, ln in enumerate(lines):
            if i == n - 1:
                out[ln.pk] = (ap - acc).quantize(Q2)
            else:
                share = (ap / n).quantize(Q2)
                out[ln.pk] = share
                acc += share
        return out
    acc = Decimal("0")
    for i, ln in enumerate(lines):
        if i == len(lines) - 1:
            out[ln.pk] = (ap - acc).quantize(Q2)
        else:
            ub = Decimal(str(ln.unit_base_price))
            share = (ap * (ub / tot)).quantize(Q2)
            out[ln.pk] = share
            acc += share
    return out


def _credit_note_amounts(order, rr, OrderLine, gst_rate):
    if rr.order_line_id:
        line = OrderLine.objects.filter(pk=rr.order_line_id, order_id=order.pk).first()
        if line is None:
            return Decimal("0"), Decimal("0")
        line_base = Decimal(str(line.unit_base_price)).quantize(Q2)
        line_gst = (line_base * gst_rate).quantize(Q2)
        shares = _amount_paid_share_by_line(order, OrderLine)
        line_share = shares.get(rr.order_line_id, Decimal("0"))
        proportion = _refund_proportion(rr.amount, line_share)
        return (line_base * proportion).quantize(Q2), (line_gst * proportion).quantize(Q2)

    paid = Decimal(str(order.amount_paid)).quantize(Q2)
    proportion = _refund_proportion(rr.amount, paid)
    base = Decimal(str(order.base_price)).quantize(Q2)
    gst = Decimal(str(order.gst_amount)).quantize(Q2)
    return (base * proportion).quantize(Q2), (gst * proportion).quantize(Q2)


def forwards(apps, schema_editor):
    RefundRequest = apps.get_model("payments", "RefundRequest")
    GSTInvoice = apps.get_model("payments", "GSTInvoice")
    CreditNote = apps.get_model("payments", "CreditNote")
    Order = apps.get_model("payments", "Order")
    OrderLine = apps.get_model("payments", "OrderLine")
    SystemConfig = apps.get_model("admin_panel", "SystemConfig")

    cfg = SystemConfig.objects.order_by("pk").first()
    gst_rate = Decimal(str(getattr(cfg, "gst_rate", None) or "0.18"))

    fy_counters: dict[date, int] = {}
    existing_rr_ids = set(CreditNote.objects.values_list("refund_request_id", flat=True))
    qs = (
        RefundRequest.objects.filter(status="APPROVED")
        .exclude(pk__in=existing_rr_ids)
        .order_by("approved_at", "id")
    )

    for rr in qs.iterator(chunk_size=200):
        if not rr.approved_at:
            continue
        order = Order.objects.filter(pk=rr.order_id).first()
        if order is None:
            continue
        paid = Decimal(str(order.amount_paid)).quantize(Q2)
        if paid <= Decimal("0"):
            continue
        inv = GSTInvoice.objects.filter(order_id=order.pk).first()
        if inv is None:
            continue

        cn_base, cn_gst = _credit_note_amounts(order, rr, OrderLine, gst_rate)
        if cn_gst <= Decimal("0") and cn_base <= Decimal("0"):
            continue

        approved_date = timezone.localtime(rr.approved_at).date()
        fy_start = _indian_fy_start(approved_date)
        fy_counters[fy_start] = fy_counters.get(fy_start, 0) + 1
        n = fy_counters[fy_start]
        yy1 = fy_start.year % 100
        yy2 = (fy_start.year + 1) % 100
        cn_number = f"CN-FY{yy1:02d}{yy2:02d}-{n:05d}"

        half = (cn_gst / 2).quantize(Q2)
        if rr.order_line_id:
            shares = _amount_paid_share_by_line(order, OrderLine)
            cap = shares.get(rr.order_line_id, Decimal("0"))
        else:
            cap = paid
        proportion = _refund_proportion(rr.amount, cap)
        discount = (Decimal(str(order.discount_amount)) * proportion).quantize(Q2)

        cn = CreditNote.objects.create(
            gst_invoice_id=inv.pk,
            refund_request_id=rr.pk,
            credit_note_number=cn_number,
            hsn_sac_code=inv.hsn_sac_code,
            base_amount=cn_base,
            cgst=half,
            sgst=half,
            total_gst=cn_gst,
            discount=discount,
            grand_total=(cn_base + cn_gst).quantize(Q2),
            reason="refund_backfill",
        )
        CreditNote.objects.filter(pk=cn.pk).update(created_at=rr.approved_at)


def reverse(apps, schema_editor):
    CreditNote = apps.get_model("payments", "CreditNote")
    CreditNote.objects.filter(reason="refund_backfill").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_creditnote"),
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
