# Generated by Django 5.1.5 on 2026-05-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_credit_notes_backfill'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditnote',
            new_name='payments_cr_created_d25522_idx',
            old_name='payments_cr_created_6e2a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='creditnote',
            new_name='payments_cr_gst_inv_3d9503_idx',
            old_name='payments_cr_gst_inv_8f3c21_idx',
        ),
    ]
