# Generated by Django 5.2.13 on 2026-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_grievance',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_base_price', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=4, default=0.18, max_digits=6)),
                ('direct_commission', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('upline_commission', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('earning_cap', models.DecimalField(decimal_places=2, default=22200, max_digits=12)),
                ('sponsor_slot_expiry_days', models.PositiveIntegerField(default=20)),
                ('tds_194h_rate', models.DecimalField(decimal_places=4, default=0.02, max_digits=6)),
                ('tds_194r_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('tds_cash_trigger', models.DecimalField(decimal_places=2, default=20000, max_digits=12)),
                ('refund_window_days', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_system_config',
            },
        ),
    ]
