# Generated by Django 5.2.13 on 2026-05-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_systemconfig_default_company_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='default_company_referral_code',
            field=models.CharField(blank=True, default='', help_text='When set, overrides DEFAULT_COMPANY_REFERRAL_CODE from the environment. Empty means use the env value.', max_length=64),
        ),
    ]
