# Generated by Django 5.2.13 on 2026-04-30

from django.db import migrations, models


def backfill_ebook_status(apps, schema_editor):
    EBook = apps.get_model("courses", "EBook")
    EBook.objects.filter(is_active=True).update(status="PUBLISHED")
    EBook.objects.filter(is_active=False).update(status="DRAFT")


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebook",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ebook",
            name="thumbnail",
            field=models.FileField(
                blank=True, null=True, upload_to="ebooks/thumbnails/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="ebook",
            name="pages_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ebook",
            name="language",
            field=models.CharField(blank=True, default="English", max_length=64),
        ),
        migrations.AddField(
            model_name="ebook",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ebook",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ebook",
            name="full_pdf",
            field=models.FileField(blank=True, null=True, upload_to="ebooks/full/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="ebook",
            name="preview_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="ebooks/preview/%Y/%m/"
            ),
        ),
        migrations.RunPython(backfill_ebook_status, migrations.RunPython.noop),
    ]
