# Generated by Django 5.2.13 on 2026-05-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TdsLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year", models.CharField(max_length=7)),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tds_triggered", models.BooleanField(default=False)),
                ("tds_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tds_ledgers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tds_ledger",
            },
        ),
        migrations.AddConstraint(
            model_name="tdsledger",
            constraint=models.UniqueConstraint(
                fields=("user", "financial_year"), name="unique_user_fy"
            ),
        ),
    ]

