# Generated by Django 5.2.13 on 2026-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('DIRECT', 'Direct'), ('UPLINE_L2', 'Upline L2'), ('UPLINE_L3', 'Upline L3'), ('UPLINE_L4', 'Upline L4'), ('MILESTONE', 'Milestone')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREDITED', 'Credited'), ('REVERSED', 'Reversed'), ('HELD', 'Held')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commissions_ledger',
            },
        ),
        migrations.CreateModel(
            name='MilestoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_referrals', models.PositiveIntegerField()),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commissions_milestone',
            },
        ),
    ]
