# Generated by Django 5.2.13 on 2026-04-14 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionledger',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='source_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestonerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
