# Generated by Django 5.2.13 on 2026-04-30 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('document_type', models.CharField(blank=True, default='', max_length=128)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='1.0', max_length=64)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='legal_documents/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_acceptance_for_compliance', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agreements_legal_document',
                'ordering': ['category', 'name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberComplianceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Prefer not to say')], default='', max_length=1)),
                ('full_address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('pin_code', models.CharField(blank=True, default='', max_length=16)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(blank=True, default='', max_length=128)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('name_on_pan', models.CharField(blank=True, default='', max_length=255)),
                ('aadhar_number', models.CharField(blank=True, default='', max_length=12)),
                ('name_on_aadhar', models.CharField(blank=True, default='', max_length=255)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='kyc/pan/%Y/%m/')),
                ('aadhar_document', models.FileField(blank=True, null=True, upload_to='kyc/aadhaar/%Y/%m/')),
                ('nominee_name', models.CharField(blank=True, default='', max_length=255)),
                ('nominee_relationship', models.CharField(blank=True, default='', max_length=128)),
                ('nominee_phone', models.CharField(blank=True, default='', max_length=22)),
                ('nominee_date_of_birth', models.DateField(blank=True, null=True)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('account_type', models.CharField(blank=True, choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('NRO', 'NRO'), ('NRE', 'NRE'), ('RECURRING', 'Recurring deposit'), ('OTHER', 'Other')], default='', max_length=20)),
                ('payout_preference', models.CharField(choices=[('BANK', 'Bank'), ('UPI', 'UPI')], default='UPI', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agreements_member_compliance_profile',
            },
        ),
        migrations.CreateModel(
            name='UserAgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_accepted', models.CharField(max_length=64)),
                ('acceptance_batch_id', models.UUIDField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='agreements.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agreements_user_acceptance',
                'indexes': [models.Index(fields=['user', 'document', '-accepted_at'], name='agreements__user_id_28760b_idx')],
            },
        ),
    ]
