# Generated by Django 5.2.13 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agreements", "0001_compliance_and_agreements"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercomplianceprofile",
            name="aadhar_front",
            field=models.FileField(
                blank=True, null=True, upload_to="kyc/aadhaar/front/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="membercomplianceprofile",
            name="aadhar_back",
            field=models.FileField(
                blank=True, null=True, upload_to="kyc/aadhaar/back/%Y/%m/"
            ),
        ),
    ]
