# Generated by Django 5.2.13 on 2026-05-12 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_aadhaar_front_back'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreementAcceptanceProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_batch_id', models.UUIDField()),
                ('signature_hex', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField()),
                ('pdf_file', models.FileField(blank=True, max_length=500, null=True, upload_to='agreement_proofs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_acceptance_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agreements_user_acceptance_proof',
                'constraints': [models.UniqueConstraint(fields=('user', 'acceptance_batch_id'), name='uniq_agreement_acceptance_proof_user_batch')],
            },
        ),
    ]
