# Generated by Django 5.2.13 on 2026-05-12 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_user_agreement_acceptance_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreementAcceptanceDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_batch_id', models.UUIDField()),
                ('declaration_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_acceptance_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agreements_user_acceptance_declaration',
                'constraints': [models.UniqueConstraint(fields=('user', 'acceptance_batch_id'), name='uniq_agreement_declaration_user_batch')],
            },
        ),
    ]
