# Generated by Django 5.1.5 on 2026-05-22 08:39

from django.db import migrations, models


def _dedupe_compliance_required(apps, schema_editor):
    LegalDocument = apps.get_model("agreements", "LegalDocument")
    rows = list(
        LegalDocument.objects.filter(
            is_active=True,
            requires_acceptance_for_compliance=True,
        ).order_by("-updated_at", "-id")
    )
    if len(rows) <= 1:
        return
    keeper = rows[0]
    LegalDocument.objects.filter(
        requires_acceptance_for_compliance=True,
    ).exclude(pk=keeper.pk).update(requires_acceptance_for_compliance=False)


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_user_agreement_acceptance_declaration'),
    ]

    operations = [
        migrations.RunPython(_dedupe_compliance_required, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('requires_acceptance_for_compliance', True)), fields=('requires_acceptance_for_compliance',), name='uniq_active_compliance_required_legal_doc'),
        ),
    ]
