# Generated by Django 5.2.13 on 2026-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login'), ('KYC', 'KYC'), ('ADMIN_LOGIN', 'Admin Login')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_otp_record',
                'indexes': [models.Index(fields=['phone', 'purpose', 'created_at'], name='auth_otp_re_phone_9ebb0b_idx'), models.Index(fields=['email', 'purpose', 'created_at'], name='auth_otp_re_email_a66a32_idx')],
            },
        ),
    ]
