# Generated by Django 5.2.13 on 2026-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otprecord_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login'), ('KYC', 'KYC'), ('ADMIN_LOGIN', 'Admin Login'), ('AGREEMENT', 'Agreement')], max_length=20),
        ),
    ]
