# Generated by Django 5.1.5 on 2026-07-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_storereferrallead'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storereferrallead',
            new_name='auth_store__expires_7d4f9b_idx',
            old_name='auth_store__expires_0f0f0f_idx',
        ),
    ]
