# Generated by Django 5.1.4 on 2026-09-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_auth_store__expires_0f0f0f_idx_auth_store__expires_7d4f9b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoOtpAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='E.164 with country code, e.g. +919876543210', max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('demo_otp_code', models.CharField(help_text='Fixed 6-digit OTP accepted for this phone/email on all OTP verify flows.', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demo OTP allowlist',
                'verbose_name_plural': 'Demo OTP allowlist',
                'db_table': 'auth_demo_otp_allowlist',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), _connector='OR'), name='auth_demo_otp_phone_or_email')],
            },
        ),
    ]
