# Generated by Django 5.2.13 on 2026-04-14 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mlm_tree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='binarynode',
            name='upline_l1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline_l1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binarynode',
            name='upline_l2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline_l2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binarynode',
            name='upline_l3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline_l3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binarynode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binary_node', to=settings.AUTH_USER_MODEL),
        ),
    ]
