# Generated by GPT-5.2 on 2026-05-08

from __future__ import annotations

from collections import defaultdict

from django.db import migrations, models


def backfill_subtree_sizes(apps, schema_editor):
    BinaryNode = apps.get_model("mlm_tree", "BinaryNode")
    rows = list(
        BinaryNode.objects.all().values_list("id", "left_child_id", "right_child_id")
    )
    if not rows:
        return

    left_by_id: dict[int, int | None] = {}
    right_by_id: dict[int, int | None] = {}
    for nid, lid, rid in rows:
        left_by_id[nid] = lid
        right_by_id[nid] = rid

    # Iterative postorder across all nodes (safe for deep trees).
    subtree_size: dict[int, int] = {}
    left_size: dict[int, int] = {}
    right_size: dict[int, int] = {}

    seen: set[int] = set()
    for root_id, _, _ in rows:
        if root_id in subtree_size:
            continue
        stack: list[tuple[int, bool]] = [(root_id, False)]
        while stack:
            nid, expanded = stack.pop()
            if nid in subtree_size:
                continue
            if not expanded:
                if nid in seen:
                    # Defensive: cycle shouldn't exist, but avoid infinite loops.
                    continue
                seen.add(nid)
                stack.append((nid, True))
                lid = left_by_id.get(nid)
                rid = right_by_id.get(nid)
                if lid:
                    stack.append((lid, False))
                if rid:
                    stack.append((rid, False))
                continue

            lid = left_by_id.get(nid)
            rid = right_by_id.get(nid)
            ls = subtree_size.get(lid, 0) if lid else 0
            rs = subtree_size.get(rid, 0) if rid else 0
            left_size[nid] = ls
            right_size[nid] = rs
            subtree_size[nid] = 1 + ls + rs

    # Bulk update in batches
    ids = list(left_size.keys())
    batch = 1000
    for i in range(0, len(ids), batch):
        chunk = ids[i : i + batch]
        nodes = list(BinaryNode.objects.filter(id__in=chunk))
        for n in nodes:
            n.left_subtree_size = int(left_size.get(n.id, 0) or 0)
            n.right_subtree_size = int(right_size.get(n.id, 0) or 0)
        BinaryNode.objects.bulk_update(nodes, ["left_subtree_size", "right_subtree_size"])


class Migration(migrations.Migration):
    dependencies = [
        ("mlm_tree", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="binarynode",
            name="left_subtree_size",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="binarynode",
            name="right_subtree_size",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_subtree_sizes, migrations.RunPython.noop),
    ]

