# Generated by Django 5.2.13 on 2026-04-14 12:17

import apps.users.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('login_identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_member', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('FINANCE', 'Finance'), ('SUPPORT', 'Support'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('member_id', models.CharField(max_length=32, unique=True)),
                ('referral_code', models.CharField(max_length=16, unique=True)),
                ('referral_link', models.URLField(max_length=500)),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('CAPPED', 'Capped'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_preference', models.CharField(choices=[('BANK', 'Bank'), ('UPI', 'UPI')], default='UPI', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('direct_referral_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_referrals', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_user',
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
    ]
