# Generated by Django 5.2.13 on 2026-04-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_compliance_and_agreements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
