# Generated by Django 5.2.13 on 2026-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorSlotBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_number', models.PositiveSmallIntegerField()),
                ('total_codes', models.PositiveSmallIntegerField(default=5)),
                ('codes_redeemed', models.PositiveSmallIntegerField(default=0)),
                ('codes_expired', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sponsor_slot_batch',
            },
        ),
        migrations.CreateModel(
            name='SponsorSlotCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('SHARED', 'Shared')], default='ACTIVE', max_length=20)),
                ('shared_via', models.CharField(blank=True, choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('COPY', 'Copy')], max_length=20, null=True)),
                ('expires_at', models.DateTimeField()),
                ('unique_ips_attempted', models.JSONField(blank=True, default=list)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sponsor_slot_code',
            },
        ),
    ]
