# Generated by Django 5.2.13 on 2026-04-14 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_initial'),
        ('sponsor_slots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorslotbatch',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_slot_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorslotcode',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='sponsor_slots.sponsorslotbatch'),
        ),
        migrations.AddField(
            model_name='sponsorslotcode',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_sponsor_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorslotcode',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_sponsor_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorslotcode',
            name='redeemed_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_redemptions', to='payments.order'),
        ),
    ]
