# Generated by Cursor on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor_slots", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorslotcode",
            name="unlock_at_total_earned",
            field=models.DecimalField(
                blank=True,
                null=True,
                decimal_places=2,
                max_digits=12,
                help_text="Unlock this code once issuer wallet.total_earned reaches this amount.",
            ),
        ),
        migrations.AddField(
            model_name="sponsorslotcode",
            name="unlocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sponsorslotcode",
            name="status",
            field=models.CharField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("ACTIVE", "Active"),
                    ("REDEEMED", "Redeemed"),
                    ("EXPIRED", "Expired"),
                    ("SHARED", "Shared"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]

